name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Assuming your package-lock.json is in a subdirectory, specify the path
    - run: npm ci
      working-directory: ./CI_CD-practises-2/CI_CD-practises-2
    - run: npm run build --if-present
      working-directory: ./CI_CD-practises-2/CI_CD-practises-2
